### ISSUE TITLE
Unable to locate element: button during the processing of following people with the hashtag based script

### ISSUE THREAD

**Issue by felixfong227** [nikilkumar9/InstaBot#4]
![image](https://user-images.githubusercontent.com/13918481/53626583-0cfda100-3c41-11e9-81a4-e30af46c7431.png)

## Text version of the error message shown above

```
Following users now
Traceback (most recent call last):
  File "hashtagBased_follow.py", line 189, in <module>
    ig.follow_user()
  File "hashtagBased_follow.py", line 145, in follow_user
    follow = driver.find_element_by_css_selector('button')
  File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: button
```

Before this error message, the script can actually put a few likes into some of the photos, but after that just throw an error.

Thanks 🙇

**Comment by nikilkumar9** [comment]
Hi Felix, at the time of this error, was the Firefox driver/browser stuck on the user profile's page, or was the page not found or something else?
