### ISSUE TITLE
Fail to follow user via the hashtag based script

### ISSUE THREAD

**Issue by felixfong227** [nikilkumar9/InstaBot#5]
```
<mysql.connector.connection.MySQLConnection object at 0x1074b0fd0>


Photo Liked:  https://www.instagram.com/p/Bvi_fd3nTU-/ from user ----------  shootthefox
Remaining photos from hkphotography : 1

Photo Liked:  https://www.instagram.com/p/Bve4TR7hMkn/ from user ----------  karlie125
Remaining photos from hkphotography : 0

Following users now
Traceback (most recent call last):
  File "hashtagBased_follow.py", line 196, in <module>
    ig.follow_user()
  File "hashtagBased_follow.py", line 145, in follow_user
    follow = driver.find_element_by_css_selector('button')
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: button
```

When using the hashtag based script, it always fail at this point and time

**Comment by nikilkumar9** [comment]
Fixed.
